name: Check for updates

on:
  schedule:
    - cron: '0 * * * *'  # hourly
  workflow_dispatch:

jobs:
  check_for_changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check for update
        id: check_change
        run: |
          response=$(curl -s https://spangle-miniature-crime.glitch.me/?uid=1.7.1)  
          echo "Response: $response"

          
          
          if [[ "$response" != "tru" ]]; then
            echo "Change detected!"
            echo "change_detected=$response" >> $GITHUB_OUTPUT
          else
            echo "No change detected."
            echo "change_detected=false" >> $GITHUB_OUTPUT
          fi

  download_ipa:
    if: needs.check_for_changes.outputs.change_detected != 'false'
    runs-on: ubuntu-latest
    needs: check_for_changes
    steps:
      - name: Fetch repo html
        run: |
          URL="https://ytbshark.github.io/"
          echo "Fetching HTML from $URL..."

          IPA_URL=$(curl -s "$URL" | grep -oE 'https?://[^"]+\.ipa' | head -n 1)
      
          if [[ -z "$IPA_URL" ]]; then
            echo "No .ipa file found!"
            exit 1
          fi
          
          echo "Found IPA: $IPA_URL"
          echo "IPA_URL=$IPA_URL" >> $GITHUB_ENV 
          VERSION=$(echo "$IPA_URL" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Version: $VERSION"
          echo "IPA_VERSION=$VERSION"  >> $GITHUB_ENV 
          
      - name: Download IPA file
        run: |
          if [[ -z "$IPA_URL" ]]; then
            echo "No IPA URL found, skipping download."
            exit 1
          fi
          
          echo "Downloading IPA from $IPA_URL..."
          curl -L -o "SharkMod v$VERSION.ipa" "$IPA_URL"

  extract_dylib:
    runs-on: ubuntu-latest
    needs: download_ipa
    steps:
      - name: get ipa name
        id: get_ipa_name
        run: |
          ipa_name=$(ls | grep .ipa)
          echo "name=$ipa_name" >> $GITHUB_OUTPUT

      - name: unpack ipa
        run: unzip ${{ steps.get_ipa_name.outputs.name }}

      - name: extract dylib
        run: |
          cp Payload/agar.io.app/Frameworks/sharkmod.dylib sharkmod.dylib

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sharkmod.dylib
          path: sharkmod.dylib

      - name: Clean up workspace
        run: rm -rf Payload

  save_updated_dylib:
    runs-on: ubuntu-latest
    needs: extract_dylib
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: sharkmod.dylib
          path: sharkmod.dylib

      - name: Move dylib
        run: |
          mv sharkmod.dylib mods/shark/tweaks/sharkmod.dylib -f

      - name: Update this workflow
        run: |
          sed -i -E "s#https://spangle-miniature-crime.glitch.me/?uid=[0-9.]+#$https://spangle-miniature-crime.glitch.me/?uid={{ env.VERSION }}#" ./.github/workflows/check_updates.yml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Updated sharkmod.dylib
          add: mods/shark/tweaks/sharkmod.dylib .github/workflows/check_updates.yml

      - name: Trigger new release with main.yml
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ipa_name="${{ steps.get_ipa_name.outputs.name }}"
          release_title="${ipa_name%.ipa}"
          release_version="${release_title#SharkMod_}"
          echo "release_title=$release_title"
          echo "release_version=$release_version"
          gh workflow run ModInjector -f release_title="$release_title" -f release_body="Automatically updated Shark's mod to latest version" -f release_tag="shark-v$release_version"
